name: Use Comment Action

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  issues: write
  pull-requests: write
  
jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run Snyk IaC
        uses: douglasmendeslda/gha-synk@main  
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          snyk-token: ${{ secrets.SNYK_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}
