name: Use Comment Action

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  issues: write
  pull-requests: write
  
jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Comment on PR
        uses: douglasmendeslda/gha-synk@main  # Substitua 'owner/repo' pelo dono e nome do repositório onde a Action está hospedada
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}
