name: Use Comment Action

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  issues: write
  pull-requests: write
  
jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Checkout reusable action repo
        uses: actions/checkout@v4
        with:
          repository:  douglasmendeslda/gha-synk
          path: reusable-action-repo
