name: Snyk IaC Scan

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Snyk IaC Scan Action
        uses: douglasmendeslda/gha-synk-scan@delta
        with:
          snyk_token: ${{ secrets.SNYK_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
